WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  password VARCHAR2(128) := REPLACE('&1', '"', '""');
  already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(already_exists, -1920);
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'CREATE USER DEXA_IDENTITY IDENTIFIED BY "' || password || '"';
  EXCEPTION
    WHEN already_exists THEN NULL;
  END;
  EXECUTE IMMEDIATE 'ALTER USER DEXA_IDENTITY IDENTIFIED BY "' || password || '" ACCOUNT UNLOCK';
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER TO DEXA_IDENTITY;
ALTER USER DEXA_IDENTITY QUOTA UNLIMITED ON USERS;
EXIT
