WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  password VARCHAR2(128) := REPLACE('&1', '"', '""');
  already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(already_exists, -1920);
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'CREATE USER DEXA_ATTENDANCE IDENTIFIED BY "' || password || '"';
  EXCEPTION
    WHEN already_exists THEN NULL;
  END;
  EXECUTE IMMEDIATE 'ALTER USER DEXA_ATTENDANCE IDENTIFIED BY "' || password || '" ACCOUNT UNLOCK';
END;
/
GRANT CREATE SESSION, CREATE TABLE TO DEXA_ATTENDANCE;
GRANT EXECUTE ON MDSYS.SDO_GEOMETRY TO DEXA_ATTENDANCE;
GRANT EXECUTE ON MDSYS.SDO_POINT_TYPE TO DEXA_ATTENDANCE;
ALTER USER DEXA_ATTENDANCE QUOTA UNLIMITED ON USERS;
EXIT
