CREATE TABLE schema_migrations (
  version VARCHAR2(20 CHAR) PRIMARY KEY,
  name VARCHAR2(255 CHAR) NOT NULL,
  checksum VARCHAR2(64 CHAR) NOT NULL,
  applied_at TIMESTAMP(3) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
